### ISSUE TITLE
Remove "force" parameter when applying patches to a kubernetes resource

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/operator-rs#113]
Recently our operators started receiving errors from Kubernetes when trying to patch the status for our cluster objects:

`May 18 16:33:28.421 ERROR reconcile{resource.name=Some("simple") resource.namespace=Some("default") request_id=41526385-7540-44cc-b716-9fc2040284ae}: stackable_operator::controller: Reconciliation finished with an error, will requeue err=OperatorError { source: KubeError { source: Api(ErrorResponse { status: "Failure", message: "PatchOptions.meta.k8s.io \"\" is invalid: force: Forbidden: may not be specified for non-apply patch", reason: "Invalid", code: 422 }) } }
`

We are currently unsure why this is and have put a workaround in place, but should spend some time investigating the root cause of this.

**Comment by lfrancke** [comment]
We have a feeling that this could be related to the changes in k8s-openapi v0.12 (which have been reverted in 0.13) so we should wait with this until we're on 0.13 and try again

https://github.com/Arnavion/k8s-openapi/issues/103

**Comment by teozkr** [comment]
Patch modes are generally handled by `kube`, not `k8s-openapi`. I don't *think* we've ever had logic in place to handle this, but maybe we used to only send the `force` parameter for `Apply` payloads? Do you remember whether this issue appearing happened around a `kube` upgrade?

**Comment by teozkr** [comment]
Could also be that K8s used to silently ignore the parameter, but turned it into a hard error at some point..

**Comment by teozkr** [comment]
Okay, so.. The problem here, sadly, is that this idea of One `FooParams` To Rule Them All (https://github.com/stackabletech/operator-rs/blob/79cec28c4c3f0a4738e75a7b7192dc8429299d5e/src/client.rs#L25-L33) doesn't really work. As you've already ran into, `PatchParams` needs to be different for different contexts (`force` depends on the mode, and `field_manager` *must* be unique per context to avoid `Patch::Apply` reverting changes made by different parts of the controller).
